CREATE TABLE STUDENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL UNIQUE,
    EMAIL      VARCHAR(50)  NOT NULL UNIQUE,
    CONTACT_NO VARCHAR(15)  NOT NULL UNIQUE,
);
